import java.awt.CardLayout;
import java.awt.GraphicsDevice;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.GraphicsEnvironment;

/**
 *
 * @author ROG
 */
public class PilihGambarButtonFullscreen extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButtonFullscreen
     */
    public PilihGambarButtonFullscreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel = new javax.swing.JPanel();
        lblAnimeBiru = new javax.swing.JLabel();
        lblAnimeMerah = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        btnMerahAnime = new javax.swing.JButton();
        btnBiruAnime = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        imagePanel.setLayout(new java.awt.CardLayout());

        lblAnimeBiru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/blueAnime.png"))); // NOI18N
        imagePanel.add(lblAnimeBiru, "0");

        lblAnimeMerah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/redAnime.png"))); // NOI18N
        imagePanel.add(lblAnimeMerah, "1");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        btnMerahAnime.setText("Red Anime Wallpaper");
        btnMerahAnime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMerahAnimeActionPerformed(evt);
            }
        });
        buttonPanel.add(btnMerahAnime);

        btnBiruAnime.setText("Blue Anime Wallpaper");
        btnBiruAnime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBiruAnimeActionPerformed(evt);
            }
        });
        buttonPanel.add(btnBiruAnime);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        buttonPanel.add(btnExit);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMerahAnimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMerahAnimeActionPerformed
        CardLayout layoutGambar = (CardLayout) (imagePanel.getLayout());
        layoutGambar.show(imagePanel, "1");
    }//GEN-LAST:event_btnMerahAnimeActionPerformed

    private void btnBiruAnimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBiruAnimeActionPerformed
        CardLayout layoutGambar = (CardLayout) (imagePanel.getLayout());
        layoutGambar.show(imagePanel, "0");
    }//GEN-LAST:event_btnBiruAnimeActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PilihGambarButtonFullscreen fullFrame = new PilihGambarButtonFullscreen();
                GraphicsDevice device = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);

                fullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBiruAnime;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMerahAnime;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel lblAnimeBiru;
    private javax.swing.JLabel lblAnimeMerah;
    // End of variables declaration//GEN-END:variables
}
